### ISSUE TITLE
Last case explanation

### ISSUE THREAD

**Issue by richidubey** [gopinathmech13/calculator#1]
https://github.com/gopinathmech13/calculator/blob/914f147a98cc44c53a4191dddd6d9f714baf479e/02_calculator.py#L32

Why is printing mistake written? The code would reach this point if the input provided is wrong. So the correct thing to write would be:

print("invalid input, please try again");

**Comment by gopinathmech13** [comment]
I have updated the code . Now the comment line is written as told by you. I need to add some more exceptions to avoid wrong input of umbers ...but before that I need to study try exception chapter.

**Comment by richidubey** [comment]
Ok. Good job.

**Comment by richidubey** [comment]
I do not the see the latest commit. Did you push it?

**Comment by richidubey** [comment]
I see it now.
